/* ===== Flat index: single grid, ranked search + thumbnails + history + worksheets + review ===== */

/* ---------- Utilities ---------- */

function clamp(n, min, max){ return Math.max(min, Math.min(max, n)); }

/* Extract a numeric id we can use for filenames */
function getEntryId(entry) {
  if (entry?.id != null)  { const m = String(entry.id).match(/\d+/);  if (m) return m[0]; }
  if (entry?.num != null) { const m = String(entry.num).match(/\d+/); if (m) return m[0]; }

  const candidates = [entry?.json, entry?.file, entry?.path, entry?.href, entry?.src];
  for (const c of candidates) {
    if (!c) continue;
    const base = String(c).split('/').pop().replace(/\.[a-z0-9]+$/i, '');
    const m = base.match(/\d+/);
    if (m) return m[0];
  }
  return null;
}

/* Turn arrays/strings into token arrays */
const toArray = v =>
  Array.isArray(v) ? v :
  (v == null || v === '') ? [] :
  String(v).split(/\s*[;,/｜|]\s*| +/).filter(Boolean);

/* Progressive thumbnail loader: tries each source until one loads, else removes <img> */
function initThumb(img) {
  const list = (img.dataset.srcList || '').split('|').filter(Boolean);
  if (!list.length) { img.remove(); return; }

  let i = 0;
  img.onerror = () => {
    i += 1;
    if (i < list.length) img.src = list[i];
    else img.remove();
  };
  img.src = list[i];
}
function initAllThumbs(root = document) {
  root.querySelectorAll('img.thumb[data-src-list]').forEach(initThumb);
}

/* ---------- Recent history (last 50, unique) ---------- */

const RECENT_KEY = 'recentKanjis_v2';   // [{k:'漢', r:'かん'},{...}]
function getRecent() {
  try { return JSON.parse(localStorage.getItem(RECENT_KEY) || '[]'); } catch { return []; }
}
function setRecent(arr) {
  localStorage.setItem(RECENT_KEY, JSON.stringify(arr.slice(0, 50)));
}
function recordRecent(kanji, furigana='') {
  if (!kanji) return;
  const list = getRecent().filter(x => x.k !== kanji);
  list.unshift({ k: kanji, r: furigana || '' });
  setRecent(list);
}

/* Also record if we’re on an entry page generated by generator.py */
(function recordFromEntryMeta(){
  if (window.__ENTRY_META__ && window.__ENTRY_META__.kanji) {
    recordRecent(window.__ENTRY_META__.kanji, window.__ENTRY_META__.furigana || '');
  }
})();

/* ---------- Load homepage entries ---------- */

let READINGS_MAP = Object.create(null); // kanji -> {kun:[], on:[]}

async function loadEntries() {
  const results = document.getElementById('results');
  if (!results) return;
  results.innerHTML = 'Loading...';

  try {
    const res = await fetch('entries/index.json', { cache: 'no-store' });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json();
    results.innerHTML = '';

    const flat = Array.isArray(data) ? data : Object.values(data || {}).flat();

    // Keep a readings map for furigana
    READINGS_MAP = {};
    flat.forEach(e => {
      READINGS_MAP[e.kanji] = {
        kun: Array.isArray(e.kun) ? e.kun : toArray(e.kun),
        on:  Array.isArray(e.on)  ? e.on  : toArray(e.on)
      };
    });

    const grid = document.createElement('div');
    grid.className = 'index-grid';
    grid.id = 'index-grid';

    (flat || []).forEach(entry => {
      const kanji = entry?.kanji ?? '';
      const file  = entry?.file  ?? '';
      const gloss = entry?.gloss ?? '';

      const kunArr = toArray(entry?.kun).map(s => String(s).toLowerCase().trim());
      const onArr  = toArray(entry?.on).map(s => String(s).toLowerCase().trim());
      const searchBlob = `${kanji} ${gloss} ${kunArr.join(' ')} ${onArr.join(' ')}`.toLowerCase();

      const id = getEntryId(entry);

      const imageSources = [];
      if (entry?.image) {
        const imgPath = String(entry.image).startsWith('http') ? entry.image :
                        (entry.image.startsWith('images/') ? entry.image : `images/${entry.image}`);
        imageSources.push(imgPath);
      }
      if (id) {
        imageSources.push(
          `images/${id}.png`,
          `images/${id}.jpg`,
          `images/${id}.jpeg`,
          `images/${id}.webp`,
          `images/${id}.gif`,
          `images/${id}.svg`
        );
      }

      const drawSource = id ? `Draws/IM_${id}.png` : null;

      const div = document.createElement('div');
      div.className = 'index-item';
      div.dataset.search = searchBlob;
      div.dataset.kun = JSON.stringify(kunArr);
      div.dataset.on  = JSON.stringify(onArr);

      div.innerHTML = `
        <a class="entry-link" data-kanji="${kanji}" href="entries/${file}" title="${gloss}">${kanji}</a>
        <span class="gloss">— ${gloss}</span>
        ${imageSources.length ? `<img class="thumb main" alt="" loading="lazy" decoding="async"
           data-src-list="${imageSources.join('|')}">` : ''}
        ${drawSource ? `<img class="thumb draw" alt="" loading="lazy" decoding="async"
           data-src-list="${drawSource}">` : ''}
      `;
      grid.appendChild(div);
    });

    if (grid.children.length) {
      results.appendChild(grid);
      initAllThumbs(grid);

      // Record when a kanji link is clicked (better signal of "searched")
      grid.addEventListener('click', (e) => {
        const a = e.target.closest('a.entry-link');
        if (!a) return;
        const kj = a.dataset.kanji || a.textContent.trim();
        const r = pickFurigana(kj);
        recordRecent(kj, r);
      });
    } else {
      results.textContent = 'No entries found yet.';
    }

    // Add right-side minimalist buttons on homepage
    addSideButtons();
  } catch (err) {
    console.error(err);
    results.textContent = 'No entries found yet.';
  }
}

/* ---------- Search (ranked) ---------- */

function searchEntries() {
  const q = (document.getElementById('search')?.value || '').trim().toLowerCase();
  const grid = document.getElementById('index-grid');
  if (!grid) return;

  const nodes = Array.from(grid.querySelectorAll('.index-item'));
  if (!nodes.length) return;

  const ranked = [];

  nodes.forEach((item, idx) => {
    item.classList.remove('exact-reading');

    if (!q) {
      item.style.display = '';
      ranked.push({ el: item, score: 0, idx });
      return;
    }

    const kun  = JSON.parse(item.dataset.kun || '[]');
    const on   = JSON.parse(item.dataset.on  || '[]');
    const blob = item.dataset.search || '';

    const exactReadingHit  = kun.includes(q) || on.includes(q);
    const startsReadingHit = !exactReadingHit && (kun.some(s => s.startsWith(q)) || on.some(s => s.startsWith(q)));
    const generalHit       = !exactReadingHit && !startsReadingHit && blob.includes(q);

    let score = -1;
    if (exactReadingHit) score = 300;
    else if (startsReadingHit) score = 200;
    else if (generalHit) score = 100;

    if (score >= 0) {
      item.style.display = '';
      if (exactReadingHit) item.classList.add('exact-reading');
      ranked.push({ el: item, score, idx });
    } else {
      item.style.display = 'none';
    }
  });

  ranked.sort((a, b) => (b.score - a.score) || (a.idx - b.idx));
  ranked.forEach(({ el }) => grid.appendChild(el));
}

/* Debounce + hotkeys, then initial run */
const debounce = (fn, ms = 120) => { let t; return (...args) => { clearTimeout(t); t = setTimeout(() => fn(...args), ms); }; };

function attachSearch() {
  const box = document.getElementById('search');
  const clearBtn = document.getElementById('clearSearch');
  if (!box) return;

  const params = new URLSearchParams(location.search || location.hash.slice(1));
  const q = (params.get('q') || '').trim();
  if (q) box.value = q;

  const run = debounce(searchEntries, 120);
  box.addEventListener('input', run);
  box.addEventListener('keydown', e => { if (e.key === 'Escape') { box.value = ''; searchEntries(); } });
  clearBtn?.addEventListener('click', () => { box.value = ''; box.focus(); searchEntries(); });

  window.addEventListener('keydown', e => {
    const tag = document.activeElement?.tagName;
    if (e.key === '/' && tag !== 'INPUT' && tag !== 'TEXTAREA') { e.preventDefault(); box.focus(); }
  });

  searchEntries();
}

/* ---------- Stroke-order inline player (below big kanji) ---------- */

function initStrokePlayers(root = document){
  root.querySelectorAll('.stroke-gif').forEach(host => {
    const src = host.getAttribute('data-stroke-src');
    const btn = host.querySelector('.stroke-play');
    if (!src || !btn) return;

    let playing = false;
    let img = null;
    let stopTimer = null;

    function stop(){
      playing = false;
      clearTimeout(stopTimer);
      stopTimer = null;
      host.classList.remove('playing');
      if (img) { img.remove(); img = null; }
      btn.style.display = '';
    }

    function start(){
      playing = true;
      btn.style.display = 'none';
      host.classList.add('playing');
      img = new Image();
      img.alt = 'stroke order';
      img.loading = 'eager';
      img.decoding = 'async';
      img.src = src + (src.includes('?') ? '&' : '?') + Date.now(); // bust GIF cache
      host.appendChild(img);
      // stop after ~40s
      stopTimer = setTimeout(stop, 40000);
    }

    btn.addEventListener('click', (e) => { e.preventDefault(); start(); });
    host.addEventListener('click', (e) => {
      // Allow clicking the GIF area to stop
      if (playing && e.target !== btn) stop();
    });
  });
}

/* ---------- Furigana helper ---------- */

function pickFurigana(kanji){
  const rec = READINGS_MAP[kanji];
  if (!rec) return '';
  const kun = Array.isArray(rec.kun) ? rec.kun : [];
  const on  = Array.isArray(rec.on)  ? rec.on  : [];
  if (kun.length) return kun[0];
  if (on.length)  return on[0];
  return '';
}

/* ---------- Right-margin minimalist buttons (iPad-friendly) ---------- */

function addSideButtons(){
  if (document.getElementById('side-actions')) return;
  if (!document.getElementById('results')) return; // homepage only

  const box = document.createElement('div');
  box.id = 'side-actions';
  box.innerHTML = `
    <button class="side-btn" id="ws6">6字シート</button>
    <button class="side-btn" id="wsPick">選択してシート</button>
    <button class="side-btn" id="review40">40字レビュー</button>
  `;
  document.body.appendChild(box);

  document.getElementById('ws6').addEventListener('click', () => {
    const rec = getRecent().map(x => x.k);
    const list = rec.slice(0, 6);
    if (!list.length) { alert('No recent kanji yet.'); return; }
    openWorksheet(list, 'Practice (Last 6)');
  });

  document.getElementById('wsPick').addEventListener('click', openPickerModal);

  document.getElementById('review40').addEventListener('click', () => {
    const list = getRecent().slice(0, 40);
    if (!list.length) { alert('No recent kanji yet.'); return; }
    openReviewWindow(list);
  });
}

/* ---------- Selection modal (pick up to 10) ---------- */

function openPickerModal(){
  const overlay = document.createElement('div');
  overlay.className = 'picker-overlay';
  const recent = getRecent(); // [{k,r},...]

  const htmlItems = recent.slice(0, 30).map((x,i) => `
    <label class="pick-item">
      <input type="checkbox" value="${x.k}" data-furi="${(x.r||'').replace(/"/g,'&quot;')}">
      <span class="pick-kanji">${x.k}</span>
      ${x.r ? `<span class="pick-furi">${x.r}</span>` : ''}
    </label>
  `).join('');

  overlay.innerHTML = `
    <div class="picker">
      <div class="pick-head">
        <div>Pick up to 10 kanji</div>
        <button type="button" class="pick-close" aria-label="Close">×</button>
      </div>
      <div class="pick-grid">${htmlItems || '<div class="pick-empty">No recent kanji yet.</div>'}</div>
      <div class="pick-actions">
        <button class="pick-submit">Generate Worksheet</button>
      </div>
    </div>
  `;
  document.body.appendChild(overlay);

  const close = () => overlay.remove();
  overlay.querySelector('.pick-close').addEventListener('click', close);
  overlay.addEventListener('click', (e) => { if (e.target === overlay) close(); });

  const boxes = Array.from(overlay.querySelectorAll('input[type=checkbox]'));
  overlay.querySelector('.pick-grid').addEventListener('change', () => {
    const checked = boxes.filter(b => b.checked);
    if (checked.length > 10) {
      // uncheck the one that tipped it over
      const last = checked.pop();
      last.checked = false;
    }
  });

  overlay.querySelector('.pick-submit').addEventListener('click', () => {
    const chosen = boxes.filter(b => b.checked).map(b => b.value);
    if (!chosen.length) { alert('Select at least one kanji.'); return; }
    openWorksheet(chosen, 'Practice (Picked)');
    close();
  });
}


/* ---------- Worksheet builder (A4, 6 across; bigger squares; furigana below) ---------- */
function buildWorksheetHTML(kanjiList, title='Practice (Last 6)') {
  const list = kanjiList.slice(0, 6);

  // Try to attach furigana if we cached readings earlier
  const recent = (typeof getRecent === 'function') ? getRecent() : [];
  const furiMap = Object.fromEntries(list.map(k => {
    const fromRecent = recent.find(x => x.k === k)?.r || '';
    const fromPick   = (typeof pickFurigana === 'function') ? pickFurigana(k) : '';
    return [k, fromRecent || fromPick || ''];
  }));

  const items = list.map(k => `
      <section class="ws-panel">
        <header class="ws-header">
          <span class="ws-kanji">${k}</span>
          <span class="ws-furi-below">${furiMap[k] || ''}</span>
        </header>
        <div class="ws-col"></div>
      </section>
  `).join('');

  return `<!doctype html>
<html lang="ja">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${title}</title>
<style>
  /* ---- Page & base ---- */
  @page { size: A4 portrait; margin: 12mm; }
  html,body{ margin:0; padding:0; background:#fff; -webkit-print-color-adjust:exact; print-color-adjust: exact; }
  body{ font-family:"Noto Serif JP","Hiragino Mincho ProN","Yu Mincho","Source Han Serif JP",serif; }
  .top-actions{ position:sticky; top:0; background:#fff; padding:6px 0 8px; display:flex; gap:10px; justify-content:center; border-bottom:1px solid #eee; }
  .btn{ padding:.45rem .8rem; border-radius:999px; border:1px solid #ddd; background:#f9f9f9; font-weight:600; }
  @media print{ .top-actions{ display:none !important; } }

  .ws-title{
    font-family:-apple-system,system-ui,"Hiragino Sans","Yu Gothic",sans-serif;
    font-weight:700; font-size:18px; letter-spacing:.02em;
    margin: 4mm 0 5mm; text-align:center;
  }

  /* ---- 6 panels across (fits within A4 inner width) ---- */
  .ws-wrap{
    display:grid;
    grid-template-columns: repeat(6, 27mm);   /* was 28mm */
    grid-auto-rows: 240mm;
    gap: 0mm 4mm;
    justify-content:center;
  }

  /* ---- Panel ---- */
  .ws-panel{
    break-inside:avoid;
    --header-h: 30mm;                 /* tall header for kanji + furigana */
    display:grid;
    grid-template-rows: var(--header-h) 1fr;
    padding: 2mm;
    border: .4mm solid rgba(0,0,0,.06);
    border-radius: 3mm;
    background:#fff;
  }

  /* Kanji header: vertical stack, centered */
  .ws-header{ display:flex; flex-direction:column; align-items:center; justify-content:flex-end; }
  .ws-kanji{ font-size: 20mm; line-height:1; letter-spacing:.01em; }
  .ws-furi-below{
    margin-top: 1.5mm;
    font-family:-apple-system,system-ui,"Hiragino Sans","Yu Gothic",sans-serif;
    font-size:4.6mm;
    color:rgba(0,0,0,.30);            /* fading gray */
    white-space:nowrap;
  }

  /* Practice column fills to bottom */
  .ws-col{ display:flex; flex-direction:column; gap: 2.2mm; height: 100%; }

  /* ---- Bigger practice squares ---- */
  .ws-cell{
    width: 18mm;                       /* was 15.5mm */
    height: 18mm;                      /* was 15.5mm */
    border: .45mm solid rgba(0,0,0,.14);
    border-radius: 1.6mm;
    background:
      linear-gradient(to right, rgba(0,0,0,.12), rgba(0,0,0,.12)) center/0.45mm 100% no-repeat,
      linear-gradient(to bottom, rgba(0,0,0,.12), rgba(0,0,0,.12)) center/100% 0.45mm no-repeat,
      linear-gradient(to right, rgba(0,0,0,.06) 1px, transparent 1px) center/100% 1px no-repeat,
      linear-gradient(to bottom, rgba(0,0,0,.06) 1px, transparent 1px) center/1px 100% no-repeat;
  }

  @media (max-width: 1024px){
    .ws-kanji{ font-size: clamp(30px, 6.8vw, 20mm); }
  }
</style>
</head>
<body>
  <div class="top-actions">
    <button class="btn" onclick="window.print()">Print</button>
    <button class="btn" onclick="window.close()">Close</button>
  </div>
  <div class="ws-title">${title}</div>
  <main class="ws-wrap">
    ${items}
  </main>

  <script>
    // Fill each practice column with as many squares as fit exactly to the bottom.
    function fillAllColumns(){
      document.querySelectorAll('.ws-col').forEach(col => {
        const tmp = document.createElement('div');
        tmp.className = 'ws-cell'; tmp.style.visibility = 'hidden';
        col.appendChild(tmp);
        const cellH = tmp.getBoundingClientRect().height;
        col.removeChild(tmp);

        const styles = getComputedStyle(col);
        const gap = parseFloat(styles.gap || styles.rowGap || '0');

        col.innerHTML = '';
        const avail = col.getBoundingClientRect().height;
        const n = Math.max(1, Math.floor((avail + gap) / (cellH + gap)));
        const frag = document.createDocumentFragment();
        for (let i = 0; i < n; i++){ const c = document.createElement('div'); c.className = 'ws-cell'; frag.appendChild(c); }
        col.appendChild(frag);
      });
    }

    window.addEventListener('load', () => { setTimeout(fillAllColumns, 0); });
    window.addEventListener('resize', () => { setTimeout(fillAllColumns, 50); });
    window.addEventListener('beforeprint', fillAllColumns);
  </script>
</body>
</html>`;
}






/* Open a new window with the worksheet (robust against popup quirks) */
function openWorksheet(kanjiList, title = 'Practice') {
  const html = buildWorksheetHTML(kanjiList, title);

  let w = window.open('about:blank', '_blank');
  if (w && !w.closed) {
    try {
      w.document.open('text/html', 'replace');
      w.document.write(html);
      w.document.close();
      return;
    } catch (e) {}
  }
  try {
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    w = window.open(url, '_blank');
    if (!w || w.closed) {
      alert('Popup was blocked. Please allow popups for this site and try again.');
    }
  } catch (e) {
    alert('Could not open the worksheet window. Please allow popups and try again.');
  }
}

/* ---------- REVIEW window: last 40 kanji (big) with furigana on the LEFT ---------- */

function buildReviewHTML(items){
  const blocks = items.map(x => {
    const k = x.k; const f = x.r || pickFurigana(k) || '';
    return `
      <div class="rv-item">
        ${f ? `<span class="rv-furi-left">${f}</span>` : `<span class="rv-furi-left rv-fade">&nbsp;</span>`}
        <span class="rv-kanji">${k}</span>
      </div>
    `;
  }).join('');

  return `<!doctype html>
<html lang="ja">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Review (Last 40)</title>
<style>
  html,body{ margin:0; padding:0; background:#fff; color:#222; -webkit-text-size-adjust: 100%; }
  body{ font-family: "Noto Serif JP","Hiragino Mincho ProN","Yu Mincho","Source Han Serif JP",serif; }

  .rv-top{
    position: sticky; top:0; background:#fff; border-bottom:1px solid #eee;
    display:flex; gap:10px; justify-content:center; padding:8px 0; margin-bottom:8px;
  }
  .btn{ padding:.45rem .8rem; border-radius: 999px; border:1px solid #ddd; background:#f9f9f9; font-weight:600; }

  .rv-wrap{
    padding: 12px;
    display:grid;
    grid-template-columns: repeat(auto-fit, minmax(120px, 1fr));
    gap: 10px 14px;
  }
  .rv-item{
    display:flex; align-items:center; gap:8px; justify-content:flex-start;
    background: #fafafa;
    border: 1px solid #eee;
    border-radius: 10px;
    padding: 10px 12px;
  }
  .rv-furi-left{
    font-family: -apple-system, system-ui, "Hiragino Sans","Yu Gothic", sans-serif;
    font-size: 12px; color: rgba(0,0,0,.38);
    width: 34%;
    text-align: right;
  }
  .rv-furi-left.rv-fade{ color: transparent; }

  .rv-kanji{
    font-size: clamp(42px, 9vw, 72px);
    line-height: 1;
    letter-spacing: .01em;
  }

  @media (max-width: 820px){
    .rv-item{ gap:6px; }
    .rv-furi-left{ width: 38%; font-size: 12px; }
  }
</style>
</head>
<body>
  <div class="rv-top">
    <button class="btn" onclick="window.print()">Print</button>
    <button class="btn" onclick="window.close()">Close</button>
  </div>
  <div class="rv-wrap">
    ${blocks || '<div>No recent kanji yet.</div>'}
  </div>
</body>
</html>`;
}

function openReviewWindow(list){
  const html = buildReviewHTML(list);
  let w = window.open('about:blank', '_blank');
  if (w && !w.closed) {
    try {
      w.document.open('text/html', 'replace');
      w.document.write(html);
      w.document.close();
      return;
    } catch (e) {}
  }
  try {
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    w = window.open(url, '_blank');
    if (!w || w.closed) alert('Popup was blocked. Please allow popups for this site and try again.');
  } catch (e) {
    alert('Could not open the review window. Please allow popups and try again.');
  }
}

/* ---------- Boot ---------- */

window.addEventListener('load', async () => {
  await loadEntries();
  attachSearch();
  initStrokePlayers(document);
});
