name: Count and list missing json files

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'json/**'
      - '.github/workflows/count-files.yml'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Count JSONs and write reports (pure Bash)
        shell: bash
        run: |
          set -euo pipefail
          FOLDER="json"
          COUNT_FILE="json/_file_count.txt"
          MISSING_TXT="json/_missing_numbers.txt"
          MISSING_JSON="json/_missing_numbers.json"
          EXPECTED_TOTAL=1950

          mkdir -p "$FOLDER"

          # Extract numbers from filenames like 123.json or anything_123.json
          # 1) list all .json files -> filenames only
          # 2) sed pulls the trailing number before .json
          # 3) sort/uniq
          mapfile -t FOUND_NUMS < <(find "$FOLDER" -type f -iname '*.json' -printf '%f\n' \
            | sed -nE 's/^(.*_)?([0-9]+)\.json$/\2/p' \
            | sort -n | uniq)

          # Count found
          FOUND_TOTAL="${#FOUND_NUMS[@]}"
          printf '%s\n' "$FOUND_TOTAL" > "$COUNT_FILE"

          # Build missing list: seq 1..EXPECTED minus FOUND_NUMS
          # Use comm; it needs both inputs sorted & unique
          tmp_found="$(mktemp)"
          printf '%s\n' "${FOUND_NUMS[@]}" > "$tmp_found"

          tmp_expected="$(mktemp)"
          seq 1 "$EXPECTED_TOTAL" > "$tmp_expected"

          # Missing = in expected but not in found
          mapfile -t MISSING < <(comm -23 "$tmp_expected" "$tmp_found")

          # Write missing numbers (newline-separated)
          if ((${#MISSING[@]})); then
            printf '%s\n' "${MISSING[@]}" > "$MISSING_TXT"
          else
            : > "$MISSING_TXT"   # empty file if none missing
          fi

          # JSON summary
          MISSING_COUNT="${#MISSING[@]}"
          {
            echo "{"
            echo "  \"folder\": \"${FOLDER}\","
            echo "  \"pattern\": \"(^|_)<NUMBER>.json\","
            echo "  \"expected_total\": ${EXPECTED_TOTAL},"
            echo "  \"found_total\": ${FOUND_TOTAL},"
            echo "  \"missing_count\": ${MISSING_COUNT},"
            echo -n "  \"missing_numbers\": ["
            if ((${#MISSING[@]})); then
              paste -sd, <(printf '%s\n' "${MISSING[@]}")
            fi
            echo "]"
            echo "}"
          } > "$MISSING_JSON"

          rm -f "$tmp_found" "$tmp_expected"

      - name: Commit results (skip CI)
        shell: bash
        run: |
          set -euo pipefail

          # Ensure outputs are not ignored
          for p in json/_file_count.txt json/_missing_numbers.txt json/_missing_numbers.json; do
            if git check-ignore -q "$p"; then
              echo "!$p" >> .gitignore
              git add .gitignore
            fi
          done

          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f json/_file_count.txt json/_missing_numbers.txt json/_missing_numbers.json
          if ! git diff --cached --quiet; then
            git commit -m "chore: update json count & missing list [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
