name: Count and list missing json files

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'json/**'
      - '.github/workflows/count-files.yml'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Count JSONs and write reports
        shell: bash
        run: |
          set -euo pipefail
          FOLDER_PATH="json"
          COUNT_FILE="json/_file_count.txt"
          MISSING_TXT="json/_missing_numbers.txt"
          MISSING_JSON="json/_missing_numbers.json"
          EXPECTED_TOTAL=1950

          mkdir -p "$FOLDER_PATH"

          # --- Python block to compute counts & missing numbers ---
          python3 - <<'PY'
import os, re, json
folder = "json"
count_file = "json/_file_count.txt"
missing_txt = "json/_missing_numbers.txt"
missing_json = "json/_missing_numbers.json"
expected_tot = 1950

pat = re.compile(r'(?:^|_)(\d+)\.json$', re.IGNORECASE)
nums = set()
for root, _, files in os.walk(folder):
    for f in files:
        m = pat.search(f)
        if m:
            nums.add(int(m.group(1)))

expected = set(range(1, expected_tot + 1))
missing  = sorted(expected - nums)

os.makedirs(os.path.dirname(count_file), exist_ok=True)
with open(count_file, "w", encoding="utf-8") as f:
    f.write(str(len(nums)) + "\n")

with open(missing_txt, "w", encoding="utf-8") as f:
    f.write("\n".join(map(str, missing)) + ("\n" if missing else ""))

summary = {
    "folder": folder,
    "pattern": "(^|_)<NUMBER>.json",
    "expected_total": expected_tot,
    "found_total": len(nums),
    "missing_count": len(missing),
    "missing_numbers": missing,
}
with open(missing_json, "w", encoding="utf-8") as f:
    json.dump(summary, f, ensure_ascii=False, indent=2)

print(f"Found {len(nums)} numbered .json file(s). Missing: {len(missing)}")
PY
          # -------------------------------------------------------

      - name: Commit results (skip CI)
        shell: bash
        run: |
          set -euo pipefail
          # Ensure outputs aren’t ignored
          for p in json/_file_count.txt json/_missing_numbers.txt json/_missing_numbers.json; do
            if git check-ignore -q "$p"; then
              echo "!$p" >> .gitignore
              git add .gitignore
            fi
          done

          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f json/_file_count.txt json/_missing_numbers.txt json/_missing_numbers.json
          if ! git diff --cached --quiet; then
            git commit -m "chore: update json count & missing list [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
