name: Count files in json folder

on:
  push:
    branches: [ main, master ]
    paths:
      - "json/**"
      - ".github/workflows/count-json.yml"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure target
        run: |
          echo "FOLDER_PATH=json" >> $GITHUB_ENV
          echo "OUTPUT_FILE=json/_file_count.txt" >> $GITHUB_ENV

      - name: Count and write
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p "$(dirname "$OUTPUT_FILE")"

          if [[ ! -d "$FOLDER_PATH" ]]; then
            COUNT=0
          else
            # OPTION A: count all files in json/
            # COUNT=$(find "$FOLDER_PATH" -type f ! -name "$(basename "$OUTPUT_FILE")" | wc -l | tr -d ' ')

            # OPTION B: count only .json files (recommended)
            COUNT=$(find "$FOLDER_PATH" -type f -iname "*.json" ! -name "$(basename "$OUTPUT_FILE")" | wc -l | tr -d ' ')
          fi

          printf "%s\n" "$COUNT" > "$OUTPUT_FILE"
          echo "Counted $COUNT file(s) in '$FOLDER_PATH' → wrote $OUTPUT_FILE"

      - name: Commit if changed
        run: |
          if ! git diff --quiet -- "$OUTPUT_FILE"; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add "$OUTPUT_FILE"
            git commit -m "chore: update file count for json/"
            git push
          else
            echo "No changes to commit."
          fi
